SELECT TOP (1000) [StudentID]
      ,[studentName]
      ,[studentContact]
      ,[Courses]
      ,[CoursesList]
      ,[instructors]
      ,[Department]
      ,[Registration]
  FROM [aptech].[dbo].[StudentCoursesRegistration]